# Generated by Django 4.2.13 on 2024-06-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapeid',
            name='shape_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
