# Generated by Django 4.2.16 on 2024-11-06 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendardate',
            unique_together={('service', 'date')},
        ),
    ]
