# Generated by Django 4.2.13 on 2024-06-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_shapeid_shape_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shape',
            options={'ordering': ['shape_id', 'shape_pt_sequence']},
        ),
        migrations.AlterModelOptions(
            name='shapeid',
            options={'ordering': ['shape_id']},
        ),
        migrations.AddField(
            model_name='shapeid',
            name='shape_pt_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shapeid',
            name='shape_pt_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shapeid',
            name='shape_pt_sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
