# Generated by Django 4.2.13 on 2024-07-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_shape_options_alter_shapeid_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.IntegerField()),
                ('stop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stop')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trip')),
            ],
        ),
    ]
