# Generated by Django 4.2.13 on 2024-07-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tripupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripupdate',
            name='id',
        ),
        migrations.AlterField(
            model_name='tripupdate',
            name='stop_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tripupdate',
            name='trip_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
