# Generated by Django 4.2.13 on 2024-07-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_tripupdate_id_alter_tripupdate_stop_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripUpdate',
        ),
        migrations.AlterField(
            model_name='route',
            name='route_id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
