# Generated by Django 4.2.13 on 2024-06-10 15:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_premium_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=255)),
                ('agency_url', models.URLField()),
                ('agency_timezone', models.CharField(max_length=255)),
                ('agency_lang', models.CharField(blank=True, max_length=2, null=True)),
                ('agency_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('service_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
                ('start_date', models.BooleanField()),
                ('end_date', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_publisher_name', models.CharField(max_length=255)),
                ('feed_publisher_url', models.URLField()),
                ('feed_lang', models.CharField(max_length=10)),
                ('feed_start_date', models.DateField()),
                ('feed_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('route_short_name', models.CharField(max_length=10)),
                ('route_long_name', models.CharField(max_length=255)),
                ('route_desc', models.CharField(max_length=255)),
                ('route_type', models.IntegerField()),
                ('route_color', models.CharField(blank=True, max_length=6, null=True)),
                ('route_text_color', models.CharField(blank=True, max_length=6, null=True)),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.CharField(max_length=255)),
                ('shape_pt_lat', models.FloatField()),
                ('shape_pt_lon', models.FloatField()),
                ('shape_pt_sequence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('stop_sequence', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stop_headsign', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_type', models.IntegerField(blank=True, null=True)),
                ('drop_off_type', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('trip_headsign', models.CharField(blank=True, max_length=255, null=True)),
                ('direction_id', models.IntegerField(blank=True, null=True)),
                ('wheelchair_accessible', models.IntegerField()),
                ('brigade', models.IntegerField()),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.route')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.calendar')),
                ('shape_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shape')),
            ],
        ),
        migrations.RemoveField(
            model_name='stop',
            name='bus_stops',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='tramway_stops',
        ),
        migrations.AddField(
            model_name='stop',
            name='stop_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='stop_id',
            field=models.CharField(default='default_stop_id', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='stop',
            name='stop_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='stop_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='stop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='zone_id',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PublicTransportType',
        ),
        migrations.AddField(
            model_name='stoptime',
            name='stop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stop'),
        ),
        migrations.AddField(
            model_name='stoptime',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trip'),
        ),
    ]
