# Generated by Django 4.2.13 on 2024-06-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_agency_calendar_feedinfo_route_shape_stoptime_trip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_desc',
            field=models.CharField(max_length=9999),
        ),
    ]
