# Generated by Django 4.2.13 on 2024-06-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_route_route_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='start_date',
            field=models.DateField(),
        ),
    ]
