# Generated by Django 4.2.13 on 2024-06-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_calendar_end_date_alter_calendar_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='end_date',
            field=models.DateField(default=20240616),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='start_date',
            field=models.DateField(default=20240610),
        ),
    ]
