version: '3.3'

services:
  scheduler_db:
    image: postgres:17
    container_name: scheduler_db
    environment:
      - POSTGRES_DB=scheduler_db
      - POSTGRES_USER=scheduler_user
      - POSTGRES_PASSWORD=scheduler_password
    ports:
      - 5432:5432
    volumes:
      - postgres-scheduler-volume:/var/lib/postgresql/data

  scheduler:
    image: scheduler
    container_name: backend_work
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "sleep 10 && /backend/api/scripts/run.sh"
    volumes:
      - .:/backend
    ports:
      - 8000:8000
    depends_on:
      - scheduler_db
      - redis
      - celery

  redis:
    image: redis:latest
    container_name: redis_work
    ports:
      - 6379:6379
    command: redis-server --bind 0.0.0.0

  celery:
    image: scheduler
    container_name: celery_work
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "celery -A backend worker --loglevel=info & celery -A backend beat --loglevel=info"
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
    depends_on:
      - scheduler_db
      - redis


volumes:
  postgres-scheduler-volume:
