version: '3.3'

services:
  scheduler_db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=scheduler_db
      - POSTGRES_USER=scheduler_user
      - POSTGRES_PASSWORD=scheduler_password
    ports:
      - 5432:5432
    volumes:
      - postgres-scheduler-volume:/var/lib/postgresql/data

  scheduler:
    image: scheduler
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "./run.sh"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - scheduler_db
      - redis
      - celery

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server --bind 0.0.0.0

  celery:
    image: scheduler
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "celery -A backend worker --loglevel=info & celery -A backend beat --loglevel=info"
    volumes:
      - .:/code
    depends_on:
      - scheduler_db
      - redis


volumes:
  postgres-scheduler-volume:
